### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by paulmorabito** [manbearwiz/youtube-dl-server#27] opened 2019-02-16 06:50 UTC
Hi,

I'm getting the following error:

10.42.0.0 - - [15/Feb/2019 21:31:24] "GET / HTTP/1.1" 404 728
10.42.0.0 - - [15/Feb/2019 21:31:35] "GET /youtube-dl HTTP/1.1" 200 3593
10.42.0.0 - - [15/Feb/2019 21:31:35] "GET /youtube-dl/static/style.css HTTP/1.1" 200 134
Added url https://youtu.be/MazyUAhGemk to the download queue
10.42.0.0 - - [15/Feb/2019 21:31:41] "POST /youtube-dl/q HTTP/1.1" 200 92
[youtube] MazyUAhGemk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name does not resolve> (caused by URLError(gaierror(-2, 'Name does not resolve')))
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
encode_chunked=req.has_header('Transfer-encoding'))
File "/usr/local/lib/python3.7/http/client.py", line 1229, in request

This is with any youtube video. I can ping youtu.be from a shell within the countainer and it works.

I'm deploying this container on a Rancher managed Kubernetes cluster if this makes a difference.

Any help would be very appreciated!

**Comment by manbearwiz** [comment] 2019-03-08 05:06
Have you tried with a non shortened URL? ie https://www.youtube.com/watch?v=MazyUAhGemk ? Not sure redirects work.

**Comment by paulmorabito** [comment] 2019-03-08 06:05
I tried with both, yes. It seems to occur intermittently and restarting the
deployment/container fixes it. It's possibly something with the kubernetes
networking or dns but very strange that it only affects only youtube-dl.

**Comment by manbearwiz** [comment] 2019-03-19 05:52
Closing for now as I am unable to reproduce it and it is happening intermittently. Happy to reopen it if other people are experiencing it and have idea of what may be done.

**Closed by manbearwiz** 2019-03-19 05:52 UTC
Labels: question
